title: Andy White
email: 
description: The nerd geek
baseurl: "" # the subpath of your site, e.g. /blog
url: http://andywhite.org
twitter_username: doctorpod
github_username:  doctorpod
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.locsc

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /blog

disqus:
  shortname: andywhite
